version: '3.8'

services:
  mariadb:
    container_name: mariadb_cont
    build: ./requirements/mariadb/
    expose:
      - "3306"
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart: always
networks:
  inception:
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/data/mariadb/'