version: '3.8'

services:
  mariadb:
    container_name: mariadb_cont
    build: ./requirements/mariadb/
    expose:
      - "3306"
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart: always
  wordpress:
    container_name: wordpress_cont
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    expose:
      - "9000"
    env_file:
      - .env
    volumes:
      - wp:/var/www
    networks:
      - inception
    restart: always
  nginx:
    container_name: nginx_cont
    build: ./requirements/nginx/
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - wp:/var/www
    networks:
      - inception
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/data/mariadb/'
  wp:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/data/wordpress/'