version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb_cont
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile # no sería necesario
    expose:
      - "3306"
    env_file:
      - .env
    volumes:
      - db:/var/lib/mariadb
    networks:
      - inception
    restart: always
  wordpress:
    image: wordpress
    container_name: wordpress_cont
    build: ./requirements/wordpress
    expose:
      - "9000"
    env_file:
      - .env
    volumes:
      - wp:/var/www
    networks:
      - inception
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/requirements/mariadb/vol'
  wp:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/requirements/wordpress/vol'
